// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyiczzkxmevimefllupq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5aWN6emt4bWV2aW1lZmxsdXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzAwMTEsImV4cCI6MjA2MDA0NjAxMX0.zVBoiK__P3qHn8ua3YZnpzCMLnAW6Tof7ZYykByTUCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);